name: Dynamic Proxmox LXC Deployment

on:
  push: # Security notice - self-hosted + public: no pull request triggers! 
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-infrastructure:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup env path
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install Python dependencies 
        run: pip3 install ansible==9.5.1 proxmoxer==2.0.1 requests==2.31.0 --user

      - name: Install Ansible dependencies
        run: ansible-galaxy collection install community.proxmox==1.5.0

      - name: Deploy LXC
        env:
          PROXMOX_PASSWORD: ${{ secrets.PROXMOX_API_PASSWORD }}
          LXC_PASSWORD: ${{ secrets.LXC_ROOT_PASSWORD }}
        run: |
          ansible-playbook deploy_lxc.yml \
            -e "proxmox_password=$PROXMOX_PASSWORD" \
            -e "lxc_password=$LXC_PASSWORD"